version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.2
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    mem_limit: 256M
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:5.3.2
    container_name: broker
    links:
      - zookeeper
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$DOCKER_HOST_IP:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - JAVA_OPTIONS=-Xms128M -Xmx256M
    mem_limit: 256M
